name: kelar_flutter
description: "Mobile application that connect with IoT to solve K3 problems in office environment."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^8.1.3
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  iconsax_plus: ^1.0.0
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.3.0
  sizer: ^2.0.15
  skeletonizer: ^1.2.0
  unicons: ^2.1.1

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true