// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS5iRJKR_QIxIb-X3WsJiJ-gEAKSCevU0',
    appId: '1:499698435245:web:0e4f432f645f5b4d3fb224',
    messagingSenderId: '499698435245',
    projectId: 'sic-k3lar',
    authDomain: 'sic-k3lar.firebaseapp.com',
    storageBucket: 'sic-k3lar.appspot.com',
    measurementId: 'G-SKP780QCKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz7x7LJa6g-Gce9FORSjwETx3M3XQouXg',
    appId: '1:499698435245:android:13169d17ab5cdc9c3fb224',
    messagingSenderId: '499698435245',
    projectId: 'sic-k3lar',
    storageBucket: 'sic-k3lar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvpkI2E3rcBXde8NOBEuEta-sW7ME_Sqo',
    appId: '1:499698435245:ios:c99f068a7c386af43fb224',
    messagingSenderId: '499698435245',
    projectId: 'sic-k3lar',
    storageBucket: 'sic-k3lar.appspot.com',
    iosClientId: '499698435245-vf2mk2rv0vjised9hqal14e7rec0onpe.apps.googleusercontent.com',
    iosBundleId: 'com.sic.kelarFlutter',
  );
}
